args: Namespace(batch_size=16, checkpoint=None, model='pointMLP', msg='422-42', num_classes=40, num_points=2048, partition='generated')
==> Using device: cuda
==> Preparing data..
(6, 2048, 3)
(6, 1)
6
==> Building model..
==> RESULTS:
libibverbs: Warning: couldn't load driver 'libmlx4-rdmav34.so': libmlx4-rdmav34.so: cannot open shared object file: No such file or directory
(b'chair_ball.stl', b'chair_outside.stl', b'chair_poisson.stl', b'U_net_test_2.stl', b'U_net_test_1.stl', b'chair_shrink_wrap.stl') :

	True: [5 5 5 5 5 5]
	Pred: [12  4  4  4  4  4]
	max: 1.0
	min: -1.0
 [>................................................................]  Step: 9s474ms | Tot: 0ms | Loss: 3.830 | Acc: 0.000% (0/6) 1/1 
/home/johnstonem/.conda/envs/pointmlp/lib/python3.8/site-packages/sklearn/metrics/_classification.py:2399: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

Vanilla out: {'loss': 3.83, 'acc': 0.0, 'acc_avg': 0.0, 'time': 4}
